### ISSUE TITLE
can not build and execute in macOS

### ISSUE THREAD

**Issue by b4sh5i** [metacraft-labs/codetracer#25]
```
➜  codetracer git:(main) nix develop
do you want to allow configuration setting 'extra-substituters' to be set to 'https://metacraft-labs-codetracer.cachix.org' (y/N)?
do you want to permanently mark this value as untrusted (y/N)?
warning: ignoring untrusted flake configuration setting 'extra-substituters'.
Pass '--accept-flake-config' to trust it
do you want to allow configuration setting 'extra-trusted-public-keys' to be set to 'metacraft-labs-codetracer.cachix.org-1:6p7pd81m6sIh59yr88yGPU9TFYJZkIrFZoFBWj/y4aE=' (y/N)?
do you want to permanently mark this value as untrusted (y/N)?
warning: ignoring untrusted flake configuration setting 'extra-trusted-public-keys'.
Pass '--accept-flake-config' to trust it
evaluation warning: 'playwright' will reference playwright-driver in 25.05. Reference 'python3Packages.playwright' for the python test launcher
error: hash mismatch in fixed-output derivation '/nix/store/h5y81bdj2a6nf185qrh58lf2vzpyhjl1-yarn-cache.drv':
         specified: sha512-UWympCycvDOUSeMLO9E6HNwQWEV1pNHK7OjsFssUmTNIrY3vboXZV91xhWoLsJ/nHAcr9T91fXEBSlPXMGmA9A==
            got:    sha512-OtGypcGuUJZlek+lvBZvE33lUcipHz9xrhJ6j/SBVAwAaYRTpjZsvT4LfVn75GXIJQXCyPuicPirpzFMTO6PyQ==
error: 1 dependencies of derivation '/nix/store/gvxj802pi081brwch4l471rymsndd6b5-node-modules-derivation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/bvf7v532j4ii9109ryzw8w06dy9cpfqz-nix-shell-env.drv' failed to build
```
I'm experiencing an issue with the macOS dmg file from the releases section. When trying to run the downloaded 'CodeTracer' application, I get the error message: 'This version of 'CodeTracer' application cannot be used on this version of macOS'. I'm currently running macOS Sonoma 14.5. I also tried building from the source code in the repository but encountered the same error. Could you please look into compatibility issues with Sonoma or provide guidance on how to make it work with my system?

**Comment by alehander92** [comment]
Sorry for the late response: that's a serious issue, thanks for reporting it!

The nix build is currently broken for macOS: the hash yarn cache error is fixable, but IIRC we had a different compile error with a native module in the nixified yarn build. It would be great to fix that, but it's not a top priority for now: currently the shell script-based (non-nix) build should be functional.

The problem with the `dmg` file is more critical, we probably need to build it targeting older versions of macOS: I'll open an issue to track that!

**Comment by alehander92** [comment]
Ok: added #42 and #43 to track those (i hope the non-nix source build problem will be resolved as part of those)

**Comment by alehander92** [comment]
Ok, the new 25.03.2 release: http://downloads.codetracer.com/CodeTracer-25.03.2-arm64.dmg should fix this after merging #62 which tries to fix #42 . @b4sh5i can you please test with it(or with latest main?)

**Comment by b4sh5i** [comment]
@alehander92 I recently updated my Silicon Mac to the latest version, Sequoia 15.3.2. However, I still get the error message "'CodeTracer' is damaged and cannot be opened. You should move this item to the Trash." I think there might be an issue with the ARM build.

**Comment by Madman10K** [comment]
Tested on macOS 12 and it works now. Closing.
